# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 494640624a497476e208b97ea768e9bc460dfde4d2af12519cb83fac60905417fc3935bb515a8e3d3e28cd97b941173290f64f638c6a52821b646a391cc2b630

test:
  secret_key_base: 7b186caa72aaa34ddeea8503199ca84cc1a2bc4f4042d971a07c42fd15db88350d1f4d306f74109bb12921ea560fc8c34b0d638cc5f1a0af3d1f5574f99e1f98

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
